[technote]
id = "SQR-000"
series_id = "SQR"
# title = "The *technical note* system"
canonical_url = "https://sqr-000.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-000"
github_default_branch = "master"
date_created = "2015-11-18T00:00:00Z"
date_updated = "2015-11-23"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"

[[technote.authors]]
name.given = "Jonathan"
name.family = "Sick"
orcid = "https://orcid.org/0000-0003-3001-676X"
affiliations = [
    { name = "Rubin Observatory", ror = "https://ror.org/048g3cy84" }
]

[technote.status]
state = "deprecated"
note = "This is a comment about the status of this document."

[[technote.status.supersceding_urls]]
url = "https://sqr-000.lsst.io/"
title = "The technical note system"

[[technote.status.supersceding_urls]]
url = "https://sqr-006.lsst.io/"
